accessing
exception: anException
	
	value := anException.